const translations = {
  english: {
    LOGIN_SUCCESS: "Sign in successfully",
    LOGOUT_SUCCESS: "Logged out successfully",
    NEED_EMAIL_VERIFY: "Need to verify your email",
    NEED_VERIFY_EMAIL: "Need a registered verify email",
    VERIFY_EMAIL_SEND_OTP: "OTP send to your email successfully",
    VERIFY_PHONE_SEND_OTP: "OTP send to your phone successfully",
    SIGNUP_SUCCESS: "Sign up successfully",
    SIGNUP_SUCCESS_ADMIN: "Admin Registration successfully",
    REGISTRATION_SUCCESS: "Verification code sent on mail",
    DEFAULT_ERROR: "Something went wrong!",
    DEFAULT_SUCCESS: "Data fetch successfully",
    NO_DATA_FOUND: "No data found!",
    INVALID_OTP: "Invalid OTP",
    SUCCESS_OTP: "OTP verified successfully",
    All_CAMPUS: "Campus list",
    All_DATA: "Grades, Classrooms and Teachers list",
    All_SCHOOL: "School list",
    All_OFFSETS: "Offset list",
    NOTIFICATION_SEND_SUCCESS: "Notification send successfully",
    UPDATE_CMS: "CMS update successfully",
    ADD_SUCCESS: "Added successfully",
    UPDATE_TIPS: "Tips update successfully",
    UPDATE_OFFSET: "Offset update successfully",
    NOT_A_ADMIN: "You are not an admin !",
    NOT_A_USER: "You are not a user !",
    FORGOT_EMAIL_SENT: "OTP sent on your mail",
    SUBMIT_SUCCESS: "Submitted successfully",
    INCORRECT_PASSWORD: "Provide a valid password!",
    RESET_PASSWORD: "Password changed successfully",
    RESET_PASSWORD_FAILED: "Password reset failed!",
    MATCH_PASSWORD_CONFIRM_PASSWORD_FAILED: "New password and confirm password do not match, it should be same.",
    CHANGE_PASSWORD: "Password changed successfully",
    CHANGE_PASSWORD_FAILED: "Password change failed!",
    ENTER_REGISTER_EMAIL: "Enter registered email",
    SUCCESS: "Success",
    ERROR_GET_PROFILE: "Unable to get profile",
    UPDATED_SUCCESSFULLY: "Updated successfully",
    KIDS_ADDED_SUCCESSFULLY: "Kids added successfully",
    CARDS_ADDED_SUCCESSFULLY: "Cards added successfully",
    USER_BLOCK_SUCCESSFULLY: "User block successfully",
    USER_UNBLOCK_SUCCESSFULLY: "User unblock successfully",
    DELETED_SUCCESSFULLY: "Deleted successfully",
    All_CATEGORY: "All survey category fetched successfully",
    All_MENU_CATEGORY: "All menu category fetched successfully",
    All_CMS: "All cms fetched successfully",
    EMAIL_ALLREADY_EXIST: "Email already taken",
    PHONE_ALLREADY_EXIST: "Phone number already taken",
    USER_ALLREADY_DELETED: "User not found",
    PLEASE_AUTHENTICATE: "Please authenticate",
    EMAIL_VERYFI_FAILD: "Email verification failed",
    PHONE_VERIFY_FAILED: "Phone verification failed",
    TOKEN_NOT_FOUND: "Token not found",
    USER_NOT_FOUND_WITH_EMAIL: "No users found with this email",
    ROLE_ADMIN: "Role should be Admin",
  },
  hindi: {
    LOGIN_SUCCESS: "सफलतापूर्वक साइन इन करें",
    LOGOUT_SUCCESS: "सफलतापूर्वक लॉग आउट हो गया",
    NEED_EMAIL_VERIFY: "आपके ईमेल की पुष्टि करनी होगी",
    NEED_VERIFY_EMAIL: "पंजीकृत सत्यापित ईमेल की आवश्यकता है",
    VERIFY_EMAIL_SEND_OTP: "OTP आपके ईमेल पर सफलतापूर्वक भेजा गया है",
    SIGNUP_SUCCESS: "सफलतापूर्वक साइन अप करें",
    SIGNUP_SUCCESS_ADMIN: "व्यवस्थापक पंजीकरण सफलतापूर्वक",
    REGISTRATION_SUCCESS: "पंजीकरण कोड मेल पर भेजा गया है",
    DEFAULT_ERROR: "कुछ गड़बड़ हो गई है!",
    DEFAULT_SUCCESS: "डेटा सफलतापूर्वक प्राप्त किया गया",
    NO_DATA_FOUND: "कोई डेटा नहीं मिला!",
    INVALID_OTP: "अवैध OTP",
    SUCCESS_OTP: "OTP सफलतापूर्वक सत्यापित हुआ",
    All_CAMPUS: "कैम्पस सूची",
    All_DATA: "ग्रेड, कक्षाएँ और शिक्षकों की सूची",
    All_SCHOOL: "स्कूल सूची",
    All_OFFSETS: "ऑफसेट सूची",
    NOTIFICATION_SEND_SUCCESS: "सूचना सफलतापूर्वक भेजी गई",
    UPDATE_CMS: "CMS सफलतापूर्वक अपडेट किया गया",
    ADD_SUCCESS: "सफलतापूर्वक जोड़ा गया",
    UPDATE_TIPS: "टिप्स सफलतापूर्वक अपडेट की गई",
    UPDATE_OFFSET: "ऑफसेट सफलतापूर्वक अपडेट किया गया",
    NOT_A_ADMIN: "आप एक व्यवस्थापक नहीं हैं!",
    NOT_A_USER: "आप एक उपयोगकर्ता नहीं हैं!",
    FORGOT_EMAIL_SENT: "आपके मेल पर OTP भेजा गया है",
    SUBMIT_SUCCESS: "सफलतापूर्वक सबमिट किया गया",
    INCORRECT_PASSWORD: "कृपया एक मान्य पासवर्ड प्रदान करें!",
    RESET_PASSWORD: "पासवर्ड सफलतापूर्वक बदल दिया गया",
    RESET_PASSWORD_FAILED: "पासवर्ड रीसेट असफल!",
    MATCH_PASSWORD_CONFIRM_PASSWORD_FAILED: "नया पासवर्ड और कन्फर्म पासवर्ड मेल नहीं खाते, यह समान होना चाहिए।",
    CHANGE_PASSWORD: "पासवर्ड सफलतापूर्वक बदल दिया गया",
    CHANGE_PASSWORD_FAILED: "पासवर्ड बदलने में विफल!",
    ENTER_REGISTER_EMAIL: "पंजीकृत ईमेल दर्ज करें",
    SUCCESS: "सफलता",
    ERROR_GET_PROFILE: "प्रोफाइल प्राप्त करने में असमर्थ",
    UPDATED_SUCCESSFULLY: "सफलतापूर्वक अपडेट किया गया",
    KIDS_ADDED_SUCCESSFULLY: "बच्चों को सफलतापूर्वक जोड़ दिया गया",
    CARDS_ADDED_SUCCESSFULLY: "कार्ड सफलतापूर्वक जोड़े गए",
    USER_BLOCK_SUCCESSFULLY: "उपयोगकर्ता को सफलतापूर्वक ब्लॉक किया गया",
    USER_UNBLOCK_SUCCESSFULLY: "उपयोगकर्ता को सफलतापूर्वक अनब्लॉक किया गया",
    DELETED_SUCCESSFULLY: "सफलतापूर्वक हटा दिया गया",
    All_CATEGORY: "सभी भोजन श्रेणी सफलतापूर्वक प्राप्त की गई",
    All_MENU_CATEGORY: "सभी मेनू श्रेणी सफलतापूर्वक प्राप्त की गई",
    All_CMS: "सभी CMS सफलतापूर्वक प्राप्त की गई",
    EMAIL_ALLREADY_EXIST: "ईमेल पहले से लिया गया है.",
    PHONE_ALLREADY_EXIST: "फ़ोन नंबर पहले से मौजूद है.",
    PLEASE_AUTHENTICATE: "कृपया प्रमाणित करें",
    EMAIL_VERYFI_FAILD: "ईमेल सत्यापन असफल",
    TOKEN_NOT_FOUND: "टोकन नहीं मिला",
    USER_NOT_FOUND_WITH_EMAIL: "इस ईमेल के साथ कोई उपयोगकर्ता नहीं मिला",
  },
  bengali: {
    LOGIN_SUCCESS: "সফলভাবে সাইন ইন করা হয়েছে",
    LOGOUT_SUCCESS: "সফলভাবে লগ আউট হয়েছে ",
    NEED_EMAIL_VERIFY: "আপনার ইমেইল যাচাই করতে হবে",
    NEED_VERIFY_EMAIL: "রেজিস্টারড যাচাই ইমেইল প্রয়োজন",
    VERIFY_EMAIL_SEND_OTP: "আপনার ইমেইলে OTP সফলভাবে প্রেরণ করা হয়েছে",
    SIGNUP_SUCCESS: "সফলভাবে সাইন আপ করা হয়েছে",
    SIGNUP_SUCCESS_ADMIN: "অ্যাডমিন রেজিস্ট্রেশন সফলভাবে সম্পন্ন হয়েছে",
    REGISTRATION_SUCCESS: "মেইলে প্রেরিত যাচাই কোড",
    DEFAULT_ERROR: "কিছু ভুল হয়েছে!",
    DEFAULT_SUCCESS: "তথ্য সফলভাবে প্রাপ্ত হয়েছে",
    NO_DATA_FOUND: "কোন ডেটা পাওয়া যায়নি!",
    INVALID_OTP: "অবৈধ OTP",
    SUCCESS_OTP: "OTP সফলভাবে যাচাই হয়েছে",
    All_CAMPUS: "ক্যাম্পাস তালিকা",
    All_DATA: "শ্রেণি, ক্লাসরুম এবং শিক্ষকের তালিকা",
    All_SCHOOL: "স্কুল তালিকা",
    All_OFFSETS: "অফসেট তালিকা",
    NOTIFICATION_SEND_SUCCESS: "সফলভাবে বিজ্ঞপ্তি প্রেরিত হয়েছে",
    UPDATE_CMS: "সিএমএস সফলভাবে আপডেট হয়েছে",
    ADD_SUCCESS: "সফলভাবে যোগ করা হয়েছে",
    UPDATE_TIPS: "টিপস সফলভাবে আপডেট হয়েছে",
    UPDATE_OFFSET: "অফসেট সফলভাবে আপডেট হয়েছে",
    NOT_A_ADMIN: "আপনি একটি অ্যাডমিন নন!",
    NOT_A_USER: "আপনি একটি ব্যবহারকারী নন!",
    FORGOT_EMAIL_SENT: "আপনার ইমেইলে OTP প্রেরিত হয়েছে",
    SUBMIT_SUCCESS: "সফলভাবে জমা দেওয়া হয়েছে",
    INCORRECT_PASSWORD: "দয়া করে সঠিক পাসওয়ার্ড সরবরাহ করুন!",
    RESET_PASSWORD: "পাসওয়ার্ড সফলভাবে পরিবর্তন হয়েছে",
    RESET_PASSWORD_FAILED: "পাসওয়ার্ড রিসেট ব্যর্থ!",
    MATCH_PASSWORD_CONFIRM_PASSWORD_FAILED: "নতুন পাসওয়ার্ড এবং নিশ্চিত পাসওয়ার্ড মিলছে না, এটি একই হওয়া উচিত।",
    CHANGE_PASSWORD: "পাসওয়ার্ড সফলভাবে পরিবর্তন হয়েছে",
    CHANGE_PASSWORD_FAILED: "পাসওয়ার্ড পরিবর্তন ব্যর্থ!",
    ENTER_REGISTER_EMAIL: "রেজিস্টার্ড ইমেইল দিন",
    SUCCESS: "সাফল্য",
    ERROR_GET_PROFILE: "প্রোফাইল পেতে অসমর্থ",
    UPDATED_SUCCESSFULLY: "সফলভাবে আপডেট হয়েছে",
    KIDS_ADDED_SUCCESSFULLY: "শিশুদের সফলভাবে যোগ করা হয়েছে",
    CARDS_ADDED_SUCCESSFULLY: "কার্ড সফলভাবে যোগ করা হয়েছে",
    USER_BLOCK_SUCCESSFULLY: "ব্যবহারকারী সফলভাবে ব্লক করা হয়েছে",
    USER_UNBLOCK_SUCCESSFULLY: "ব্যবহারকারী সফলভাবে আনব্লক করা হয়েছে",
    DELETED_SUCCESSFULLY: "সফলভাবে মুছে ফেলা হয়েছে",
    All_CATEGORY: "সমস্ত খাবারের বিভাগ সফলভাবে প্রাপ্ত হয়েছে",
    All_MENU_CATEGORY: "সমস্ত মেনু বিভাগ সফলভাবে প্রাপ্ত হয়েছে",
    All_CMS: "সমস্ত সিএমএস সফলভাবে প্রাপ্ত হয়েছে",
    EMAIL_ALLREADY_EXIST: "ইমেইল ইতিমধ্যে নেওয়া হয়েছে।",
    PHONE_ALLREADY_EXIST: "ফোন নম্বর ইতিমধ্যে নেওয়া হয়েছে।",
    PLEASE_AUTHENTICATE: "অনুগ্রহ করে প্রাধিকৃত করুন",
    EMAIL_VERYFI_FAILD: "ইমেইল যাচাই ব্যর্থ হয়েছে",
    TOKEN_NOT_FOUND: "টোকেন পাওয়া যায়নি",
    USER_NOT_FOUND_WITH_EMAIL: "এই ইমেইলে কোনো ব্যবহারকারী খুঁজে পাওয়া যায়নি",
  },
  spanish: {
    LOGIN_SUCCESS: "Inicio de sesión exitoso",
    LOGOUT_SUCCESS: "Cerró sesión exitosamente",
    NEED_EMAIL_VERIFY: "Necesita verificar su correo electrónico",
    NEED_VERIFY_EMAIL:
      "Necesita un correo electrónico registrado para verificar",
    VERIFY_EMAIL_SEND_OTP: "OTP enviado a su correo electrónico con éxito",
    SIGNUP_SUCCESS: "Registro exitoso",
    SIGNUP_SUCCESS_ADMIN: "Registro de administrador exitoso",
    REGISTRATION_SUCCESS: "Código de verificación enviado por correo",
    DEFAULT_ERROR: "¡Algo salió mal!",
    DEFAULT_SUCCESS: "Datos obtenidos exitosamente",
    NO_DATA_FOUND: "No se encontraron datos",
    INVALID_OTP: "OTP inválido",
    SUCCESS_OTP: "OTP verificado exitosamente",
    All_CAMPUS: "Lista de campus",
    All_DATA: "Lista de grados, aulas y profesores",
    All_SCHOOL: "Lista de escuelas",
    All_OFFSETS: "Lista de offset",
    NOTIFICATION_SEND_SUCCESS: "Notificación enviada con éxito",
    UPDATE_CMS: "Actualización de CMS exitosa",
    ADD_SUCCESS: "Añadido exitosamente",
    UPDATE_TIPS: "Consejos actualizados exitosamente",
    UPDATE_OFFSET: "Actualización de offset exitosa",
    NOT_A_ADMIN: "¡No eres un administrador!",
    NOT_A_USER: "¡No eres un usuario!",
    FORGOT_EMAIL_SENT: "OTP enviado a su correo",
    SUBMIT_SUCCESS: "Presentado exitosamente",
    INCORRECT_PASSWORD: "¡Proporcione una contraseña válida!",
    RESET_PASSWORD: "Contraseña cambiada exitosamente",
    RESET_PASSWORD_FAILED: "Error al restablecer la contraseña",
    MATCH_PASSWORD_CONFIRM_PASSWORD_FAILED: "La nueva contraseña y la contraseña de confirmación no coinciden; deberían ser las mismas.",
    CHANGE_PASSWORD: "Contraseña cambiada exitosamente",
    CHANGE_PASSWORD_FAILED: "Error al cambiar la contraseña",
    ENTER_REGISTER_EMAIL: "Ingrese el correo electrónico registrado",
    SUCCESS: "Éxito",
    ERROR_GET_PROFILE: "No se pudo obtener el perfil",
    UPDATED_SUCCESSFULLY: "Actualizado exitosamente",
    KIDS_ADDED_SUCCESSFULLY: "Niños añadidos exitosamente",
    CARDS_ADDED_SUCCESSFULLY: "Tarjetas añadidas exitosamente",
    USER_BLOCK_SUCCESSFULLY: "Usuario bloqueado exitosamente",
    USER_UNBLOCK_SUCCESSFULLY: "Usuario desbloqueado exitosamente",
    DELETED_SUCCESSFULLY: "Eliminado exitosamente",
    All_CATEGORY: "Todas las categorías de comida obtenidas exitosamente",
    All_MENU_CATEGORY: "Todas las categorías de menú obtenidas exitosamente",
    All_CMS: "Todos los CMS obtenidos exitosamente",
    EMAIL_ALLREADY_EXIST: "El número de teléfono ya existe.",
    PHONE_ALLREADY_EXIST: "Phone number already taken",
    PLEASE_AUTHENTICATE: "Por favor autentique",
    EMAIL_VERYFI_FAILD: "Verificación de correo electrónico fallida",
    TOKEN_NOT_FOUND: "Token no encontrado",
    USER_NOT_FOUND_WITH_EMAIL:
      "No se encontraron usuarios con este correo electrónico",
  },
  swahili: {
    LOGIN_SUCCESS: "Ingia katika akaunti",
    LOGOUT_SUCCESS: "Umetoka nje kwa mafanikio",
    NEED_EMAIL_VERIFY: "Unahitaji kuthibitisha barua pepe yako",
    NEED_VERIFY_EMAIL:
      "Unahitaji barua pepe ya uthibitishaji iliyosajiliwa",
    VERIFY_EMAIL_SEND_OTP: "OTP enviado a su correo electrónico con éxito",
    SIGNUP_SUCCESS: "kujisajili kwa mafanikio",
    SIGNUP_SUCCESS_ADMIN: "usajili wa msimamizi umefaulu",
    REGISTRATION_SUCCESS: "Nambari ya kuthibitisha imetumwa kwa barua",
    DEFAULT_ERROR: "kuna kitu kimeharibika!",
    DEFAULT_SUCCESS: "data imeingizwa kwa ufanisi",
    NO_DATA_FOUND: "hakuna data iliyopatikana!",
    INVALID_OTP: "OTP batili",
    SUCCESS_OTP: "OTP verificado exitosamente",
    All_CAMPUS: "Lista de campus",
    All_DATA: "Lista de grados, aulas y profesores",
    All_SCHOOL: "Lista de escuelas",
    All_OFFSETS: "Lista de offset",
    NOTIFICATION_SEND_SUCCESS: "Notificación enviada con éxito",
    UPDATE_CMS: "Actualización de CMS exitosa",
    ADD_SUCCESS: "Añadido exitosamente",
    UPDATE_TIPS: "Consejos actualizados exitosamente",
    UPDATE_OFFSET: "Actualización de offset exitosa",
    NOT_A_ADMIN: "wewe sio admin!",
    NOT_A_USER: "Wewe si mtumiaji!",
    FORGOT_EMAIL_SENT: "OTP imetumwa kwa barua pepe yako",
    SUBMIT_SUCCESS: "Presentado exitosamente",
    INCORRECT_PASSWORD: "Toa nenosiri halali!",
    RESET_PASSWORD: "Contraseña cambiada exitosamente",
    RESET_PASSWORD_FAILED: "Error al restablecer la contraseña",
    MATCH_PASSWORD_CONFIRM_PASSWORD_FAILED: "Nenosiri mpya na uthibitisho wa nenosiri hazilingani, inapaswa kuwa sawa.",
    CHANGE_PASSWORD: "Contraseña cambiada exitosamente",
    CHANGE_PASSWORD_FAILED: "Error al cambiar la contraseña",
    ENTER_REGISTER_EMAIL: "Ingrese el correo electrónico registrado",
    SUCCESS: "Éxito",
    ERROR_GET_PROFILE: "No se pudo obtener el perfil",
    UPDATED_SUCCESSFULLY: "Imesasishwa",
    KIDS_ADDED_SUCCESSFULLY: "Niños añadidos exitosamente",
    CARDS_ADDED_SUCCESSFULLY: "Tarjetas añadidas exitosamente",
    USER_BLOCK_SUCCESSFULLY: "Usuario bloqueado exitosamente",
    USER_UNBLOCK_SUCCESSFULLY: "Usuario desbloqueado exitosamente",
    DELETED_SUCCESSFULLY: "imefutwa kwa ufanisi",
    All_CATEGORY: "Todas las categorías de comida obtenidas exitosamente",
    All_MENU_CATEGORY: "Todas las categorías de menú obtenidas exitosamente",
    All_CMS: "Todos los CMS obtenidos exitosamente",
    EMAIL_ALLREADY_EXIST: "Barua pepe tayari imechukuliwa",
    PHONE_ALLREADY_EXIST: "Nambari ya simu tayari imechukuliwa",
    PLEASE_AUTHENTICATE: "tafadhali thibitisha",
    EMAIL_VERYFI_FAILD: "Verificación de correo electrónico fallida",
    TOKEN_NOT_FOUND: "ishara haijapatikana",
    USER_NOT_FOUND_WITH_EMAIL:
      "Hakuna watumiaji waliopatikana na barua pepe hii",
  },
};

// Function to get the translated phrase based on the selected language
function getTranslatedPhrase(key, language) {
  const selectedLanguage = language || "english";
  const languageTranslations = translations[selectedLanguage];
  if (languageTranslations && languageTranslations[key]) {
    return languageTranslations[key];
  }
  // Return a default message or the key itself if the translation is not found
  return `Translation not found for key: ${key}`;
}

module.exports = {
  getTranslatedPhrase,
};
